#
# Makefile for the vi5300 drivers.
#
ccflags-y				+= -Idrivers/misc/vi5300

obj-$(CONFIG_VI5300)	+= vi5300.o
vi5300-y                += vi5300_module.o vi5300_platform.o vi5300_api.o vi5300_firmware.o
